spring.application.name=ratelimiter

# PostGres config
spring.datasource.url=jdbc:postgresql://localhost:5432/ratelimiter
spring.datasource.username=postgres
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost

# Actuator
management.endpoints.web.exposure.include=health,metrics

# App
server.port=8080